### Create post
POST http://localhost:3000/api/post HTTP/1.1
Content-Type: application/json

{
    "title": "Test post 2",
    "date": "Nov 14",
    "description": "This is a wider card with supporting text below as a natural lead-in to additional content.",
    "image": "https://source.unsplash.com/random",
    "imageText": "Image Text"
}

### Get All Posts
GET http://localhost:3000/api/post

### Get On Post
GET http://localhost:3000/api/post/7RvKPf8mdl7ooMEl

### Update Post
PATCH http://localhost:3000/api/post/7RvKPf8mdl7ooMEl
Content-Type: application/json

{
    "title": "Test post 5"
}

### Delete Post
DELETE http://localhost:3000/api/post/7RvKPf8mdl7ooMEl